-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.aisles
(
    aisle_id integer NOT NULL,
    ailse character varying COLLATE pg_catalog."default",
    aisle character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT aisles_pkey PRIMARY KEY (aisle_id)
);

CREATE TABLE IF NOT EXISTS public.departments
(
    department_id integer NOT NULL,
    department character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT departments_pkey PRIMARY KEY (department_id)
);

CREATE TABLE IF NOT EXISTS public.order_products
(
    order_id integer NOT NULL,
    product_id integer NOT NULL,
    add_to_cart_order integer,
    reordered integer,
    CONSTRAINT order_products_pkey PRIMARY KEY (order_id, product_id)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    order_id integer NOT NULL,
    user_id integer,
    order_number integer,
    order_dow integer,
    order_hour_of_day integer,
    days_since_prior_order integer,
    CONSTRAINT orders_pkey PRIMARY KEY (order_id)
);

CREATE TABLE IF NOT EXISTS public.products
(
    product_id integer NOT NULL,
    product_name character varying(255) COLLATE pg_catalog."default",
    aisle_id integer,
    department_id integer,
    CONSTRAINT products_pkey PRIMARY KEY (product_id)
);

ALTER TABLE IF EXISTS public.order_products
    ADD CONSTRAINT order_products_order_id_fkey FOREIGN KEY (order_id)
    REFERENCES public.orders (order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.order_products
    ADD CONSTRAINT order_products_product_id_fkey FOREIGN KEY (product_id)
    REFERENCES public.products (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.products
    ADD CONSTRAINT products_aisle_id_fkey FOREIGN KEY (aisle_id)
    REFERENCES public.aisles (aisle_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.products
    ADD CONSTRAINT products_department_id_fkey FOREIGN KEY (department_id)
    REFERENCES public.departments (department_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;